### ISSUE TITLE
NLCD road pixels are not useful in rural areas

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter-land-cover#1]
road pixels to remove:

https://4cowg0thg6.execute-api.us-east-1.amazonaws.com/dev/preview#11/40.7818/-123.9223

![image](https://user-images.githubusercontent.com/853051/45987327-a0450180-c025-11e8-9515-f6830a3bbe05.png)

**Comment by sethfitz** [comment]
With "Developed, Low Intensity" mapped to "barren":


![image](https://user-images.githubusercontent.com/45/46098449-45bcba00-c179-11e8-8cb2-23a63122ff6c.png)

**Comment by nvkelso** [comment]
Better! Though this seems like a visual fix – we'd still face the same problem when creating the vectors?

**Comment by sethfitz** [comment]
Kauai (https://4cowg0thg6.execute-api.us-east-1.amazonaws.com/dev/preview#14/22.0491/-159.4429) exhibits the same problem, but in that case, roads are classified as "Developed, High Intensity".

When vectorizing, we'll probably want to put a threshold on the minimum size (width?) of features that are generated.

**Comment by nvkelso** [comment]
Maybe put it back to "red" then and we'll solve downstream elsewhere?

**Comment by nvkelso** [comment]
Tom and I did something useful for removing pixels:

- http://www.shadedrelief.com/shelton/e.html

**Comment by nvkelso** [comment]
The vectorization step can deal with this, closing.
