### ISSUE TITLE
Poor class transition in eastern USA at zoom 7/8

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter-land-cover#10]
https://4cowg0thg6.execute-api.us-east-1.amazonaws.com/dev/preview#7/38.805/-81.068

This light green/yellow cirlced in blue goes to yellow in zoom 8. Not sure if it should continue in zoom 8 or be reclassed in zoom 7 and earlier.

zoom 7

![image](https://user-images.githubusercontent.com/853051/46188751-eb6a4900-c29f-11e8-8d08-4e8b0293044b.png)

![image](https://user-images.githubusercontent.com/853051/46188828-456b0e80-c2a0-11e8-93be-8894e3f10500.png)

zoom 8

![image](https://user-images.githubusercontent.com/853051/46188766-f91fce80-c29f-11e8-8914-96fbe34859ab.png)

**Comment by sethfitz** [comment]
This is a discrepancy between ESACCI-LC (z7) and NLCD (z8+). Looking at the raw outputs, it's "Pasture / Hay" in NLCD (mapped to "cultivated" in the unified schema) and "Grassland" in ESACCI-LC (mapped to "grassland").

"Cropland (herbaceous cover)" is the ESACCI-LC classification that seems to correlate.

Proposed fix: map "Pasture / Hay" to "grassland".

**Comment by nvkelso** [comment]
I’m good with that.
