### ISSUE TITLE
Missing Antarctica data

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter-land-cover#11]
Following up from https://github.com/mojodna/marblecutter-land-cover/issues/8#issuecomment-429439235.

Looks like we're missing data in Antarctica.

**Comment by sethfitz** [comment]
If this was just a follow-up from #8, I addressed it by reducing the min zoom for ESACCI-LC. Low-res MODIS is preferred, but ESACCI-LC will be used for the polar regions.
