### ISSUE TITLE
Poor forest transition at high latitude between zooms 3 and 4

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter-land-cover#12]
At zoom 3 we show less forest in the far north latitudes than at zoom 4 (where 1/2 the northern areas suddenly go green). I looked at the raw source and it looks like they just disagree in the far north latitudes. 

So we either need to live with it, or use a downsampled version of the data used at zoom 4 ALSO at zooms 0-3. @mojodna How feasible is the 2nd option?

3/61.23/-186.77

![image](https://user-images.githubusercontent.com/853051/48377583-160f3600-e683-11e8-9cab-6900c08630fb.png)

4/68.54/-224.18

![image](https://user-images.githubusercontent.com/853051/48377601-232c2500-e683-11e8-9146-c3fed83a9567.png)

4/63.07/-100.69

![image](https://user-images.githubusercontent.com/853051/48377622-30491400-e683-11e8-9dbc-4ab0b5943aa2.png)

**Comment by sethfitz** [comment]
Totally feasible (thanks, overviews!) and live. MODIS 5min has been fully disabled; ESACCI-LC now starts at zoom 0.

**Comment by nvkelso** [comment]
Verified.
