### ISSUE TITLE
US-Canada border (NLCD versus other data source max zooms)

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter-land-cover#3]
https://4cowg0thg6.execute-api.us-east-1.amazonaws.com/dev/preview#10/45.1632/-73.5191

![image](https://user-images.githubusercontent.com/853051/45987282-712e9000-c025-11e8-899d-67daece32d44.png)

one more zoom in, Canada goes missing...

![image](https://user-images.githubusercontent.com/853051/45987285-74c21700-c025-11e8-83cb-6a36c3a09ade.png)

**Comment by sethfitz** [comment]
NLCD in CONUS + Alaska has a max zoom of 15 (it goes up to 19 in the Northern Mariana Islands). ESACCI-LC has a max zoom of 11.

Boosting ESACCI-LC to 15 will allow them to match at the cost of pixellation:

![image](https://user-images.githubusercontent.com/45/46100157-98987080-c17d-11e8-9f11-03a1323ccfb3.png)
