### ISSUE TITLE
glaciers ≠ water

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter-land-cover#4]
See Greenland but applies to smaller glaciers, too.

![image](https://user-images.githubusercontent.com/853051/45987267-5b20cf80-c025-11e8-8de9-707433a69550.png)

**Comment by sethfitz** [comment]
With "Snow and Ice" / "Permanent snow and ice" mapped to "barren":

![image](https://user-images.githubusercontent.com/45/46099605-0c397e00-c17c-11e8-91ca-2cb6fa163ebe.png)

**Comment by nvkelso** [comment]
Woot! But permanent snow / glaciers should have it's own classification?

**Comment by sethfitz** [comment]
Probably, yes. I was using the 8 classifications in https://github.com/mojodna/marblecutter/issues/103#issuecomment-418886917.

**Comment by sethfitz** [comment]
![image](https://user-images.githubusercontent.com/45/46106387-5c6d0c00-c18d-11e8-90e4-20360f8169bc.png)
