### ISSUE TITLE
Missing data at zooms 0, 1, 2

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter-land-cover#8]
Might need a lower rez data source for this view.

**Comment by sethfitz** [comment]
[MODIS Land Cover includes 5ʹ 𝖷 5ʹ and ½º 𝖷 ½º downsampled sources](http://glcf.umd.edu/data/lc/) that would be appropriate for this.

**Comment by sethfitz** [comment]
Both have been transcoded and cataloged, but MODIS HD (½º, nominally useful for zooms 0-2) has been disabled in favor of the 5 minute source (useful for zooms 0-5).

![image](https://user-images.githubusercontent.com/45/46890332-53319f80-ce1b-11e8-9b89-8a8c91f61efa.png)

Alas, it only goes to 84º north and 64º south, hence the polar transparency.
