### ISSUE TITLE
Funky patches in Brazil across south america

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter-land-cover#9]
At zooms 6 nd 7?

https://4cowg0thg6.execute-api.us-east-1.amazonaws.com/dev/preview#6/-24.238/-52.258

![image](https://user-images.githubusercontent.com/853051/46114557-fb066680-c1a7-11e8-9a76-eb3780436413.png)

**Comment by sethfitz** [comment]
This is ESACCI-LC competing with MODIS. I de-prioritized MODIS and the patchwork has disappeared.
